name: 'Build Stepup Test Docker image'
description: 'Builds a Stepup app for running tests'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  php_version: 
    description: 'PHP version'
    default: 'php72'
  node_version:
    description: 'Node version'
    default: 'node16'
